### ISSUE TITLE
License

### ISSUE THREAD

**Issue by TimPietrusky** [MaximeHeckel/linear-vaporwave-three.js#1]
Hey @MaximeHeckel,

thanks for this awesome project, it totally inspired me and I want to build on top of it (of course I reimplemented everything as I'm also in the process of learning ThreeJS). But I was wondering what kind of license you want for this? 

Cheers,
Tim

**Comment by MaximeHeckel** [comment]
Hey!

You can assume MIT, will add it to the repo

Good call!

**Comment by TimPietrusky** [comment]
@MaximeHeckel thank you very much 🙏
